# Generated by Django 4.2.2 on 2023-06-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_pet_group"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="pets",
            field=models.ManyToManyField(related_name="traits", to="pets.pet"),
        ),
    ]
