# Generated by Django 4.2.2 on 2023-06-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0002_trait_pets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
